"""added relationsships

Revision ID: 35b68b99e501
Revises: f82f0a7cd2b3
Create Date: 2021-04-24 17:41:33.911479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35b68b99e501'
down_revision = 'f82f0a7cd2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulas', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'formulas', 'users', ['author_id'], ['id'])
    op.add_column('parameters', sa.Column('rating_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parameters', 'formulas', ['rating_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parameters', type_='foreignkey')
    op.drop_column('parameters', 'rating_id')
    op.drop_constraint(None, 'formulas', type_='foreignkey')
    op.drop_column('formulas', 'author_id')
    # ### end Alembic commands ###
