"""empty message

Revision ID: ec1548f52672
Revises: 8958d07873c3
Create Date: 2022-06-10 22:30:23.997552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1548f52672'
down_revision = '8958d07873c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fl_name', sa.String(length=200), nullable=True),
    sa.Column('formula', sa.String(length=1024), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formulas_fl_name'), 'formulas', ['fl_name'], unique=False)
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula', sa.String(length=1024), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('par_name', sa.String(length=200), nullable=True),
    sa.Column('flag_max', sa.Integer(), nullable=True),
    sa.Column('flag_min', sa.Integer(), nullable=True),
    sa.Column('rating_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rating_id'], ['formulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parameters_par_name'), 'parameters', ['par_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parameters_par_name'), table_name='parameters')
    op.drop_table('parameters')
    op.drop_index(op.f('ix_formulas_fl_name'), table_name='formulas')
    op.drop_table('formulas')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
